### ISSUE TITLE
autoload fields should be associated to the instance object

### ISSUE THREAD

**Issue by vincentp** [CompanyBook/massive_record#18]
The auto loaded fields are associated to the class level, it means that it's never purged but aggregated. The autoload_fields option has been created to be used dynamically : with one instance I want this fields, and for another I want another fields. So the auto loaded fields should be associated within the instance.

**Comment by thhermansen** [comment]
Can I be unassigned from this one? It doesn't seem to be possible for me to do that.

**Comment by thhermansen** [comment]
Thank you, Vincent! :-)
