### ISSUE TITLE
Model.destroy_all might not destroy all

### ISSUE THREAD

**Issue by trym** [CompanyBook/massive_record#19]
After doing Update.destroy_all I had one update left, which went away when I did Update.destroy_all again.

**Comment by thhermansen** [comment]
Don't think this is related to the ORM, as the implementation of destroy_all is really easy (https://github.com/CompanyBook/massive_record/blob/develop/lib/massive_record/orm/persistence.rb)

I think this actually is a wrapper (adapter) problem, as the Scanner applies a default limit of 10: https://github.com/CompanyBook/massive_record/blob/develop/lib/massive_record/wrapper/scanner.rb. Now that's a problem meaning that all will just return 10 and not all .. which should really be corrected.

**Comment by thhermansen** [comment]
Kinda fixed in https://github.com/CompanyBook/massive_record/commit/4d23ad859f3f0422d2e05ceabad2b2ae3be40a28

Maybe we should look at it a bit more later...
