### ISSUE TITLE
Assigning invalid dates to date attributes should not raise an error

### ISSUE THREAD

**Issue by stabenfeldt** [CompanyBook/massive_record#21]
Failures:

  1) An event object should complain when given an invalid datetime
     Failure/Error: Event.make(:start_at => '99999').should have(1).error_on(:start_at)
     ArgumentError:
       invalid date
     # /Users/martins/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/date.rb:1022:in `new_by_frags'
     # /Users/martins/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/date.rb:1066:in`parse'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/bundler/gems/massive_record-12a03fea18de/lib/massive_record/orm/schema/field.rb:106:in `decode'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/bundler/gems/massive_record-12a03fea18de/lib/massive_record/orm/attribute_methods/read.rb:12:in`read_attribute'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/bundler/gems/massive_record-12a03fea18de/lib/massive_record/orm/attribute_methods/read.rb:18:in `attribute'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/activemodel-3.0.3/lib/active_model/attribute_methods.rb:276:in`start_at'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/activemodel-3.0.3/lib/active_model/errors.rb:218:in `block in add_on_blank'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/activemodel-3.0.3/lib/active_model/errors.rb:217:in`each'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/activemodel-3.0.3/lib/active_model/errors.rb:217:in `add_on_blank'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/activemodel-3.0.3/lib/active_model/validations/presence.rb:9:in`validate'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:314:in `_callback_before_213'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:419:in`_run_validate_callbacks'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/activemodel-3.0.3/lib/active_model/validations.rb:212:in `run_validations!'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/activemodel-3.0.3/lib/active_model/validations/callbacks.rb:67:in`block in run_validations!'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:413:in `_run_validation_callbacks'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/activemodel-3.0.3/lib/active_model/validations/callbacks.rb:67:in`run_validations!'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/activemodel-3.0.3/lib/active_model/validations.rb:179:in `valid?'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-rails-2.4.1/lib/rspec/rails/extensions/active_record/base.rb:36:in`errors_on'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-expectations-2.4.0/lib/rspec/matchers/have.rb:20:in `matches?'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-expectations-2.4.0/lib/rspec/expectations/handler.rb:11:in`handle_matcher'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-expectations-2.4.0/lib/rspec/expectations/extensions/kernel.rb:27:in `should'
     # ./spec/models/event_spec.rb:33:in`block (3 levels) in <top (required)>'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/example.rb:49:in `instance_eval'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/example.rb:49:in`block (2 levels) in run'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/example.rb:98:in `with_around_hooks'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/example.rb:46:in`block in run'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/example.rb:91:in `block in with_pending_capture'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/example.rb:90:in`catch'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/example.rb:90:in `with_pending_capture'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/example.rb:45:in`run'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/example_group.rb:261:in `block in run_examples'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/example_group.rb:257:in`map'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/example_group.rb:257:in `run_examples'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/example_group.rb:231:in`run'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/example_group.rb:232:in `block in run'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/example_group.rb:232:in`map'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/example_group.rb:232:in `run'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/command_line.rb:27:in`block (2 levels) in run'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/command_line.rb:27:in `map'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/command_line.rb:27:in`block in run'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/reporter.rb:12:in `report'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/core/command_line.rb:24:in`run'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/rspec-core-2.4.0/lib/rspec/monkey/spork/test_framework/rspec.rb:4:in `run_tests'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/spork-0.9.0.rc2/lib/spork/run_strategy/forking.rb:13:in`block in run'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/spork-0.9.0.rc2/lib/spork/forker.rb:21:in `block in initialize'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/spork-0.9.0.rc2/lib/spork/forker.rb:18:in`fork'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/spork-0.9.0.rc2/lib/spork/forker.rb:18:in `initialize'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/spork-0.9.0.rc2/lib/spork/run_strategy/forking.rb:9:in`new'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/spork-0.9.0.rc2/lib/spork/run_strategy/forking.rb:9:in `run'
     # /Users/martins/.rvm/gems/ruby-1.9.2-p0@companybook-front/gems/spork-0.9.0.rc2/lib/spork/server.rb:47:in`run'
     # /Users/martins/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1558:in `perform_without_block'
     # /Users/martins/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1518:in`perform'
     # /Users/martins/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1592:in `block (2 levels) in main_loop'
     # /Users/martins/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1588:in`loop'
     # /Users/martins/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1588:in `block in main_loop'

Finished in 0.87685 seconds
1 example, 1 failure

**Comment by thhermansen** [comment]
Fixed in develop. Unparsable dates and time will be set to nil.
