### ISSUE TITLE
Error when ORM tries to connect to Hbase

### ISSUE THREAD

**Issue by jamiltao** [CompanyBook/massive_record#27]
Hi,

When running any method that should read/write to Hbase (i.e. User.all ) I'm getting the following error:

NoMethodError: You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.empty?
    from
/Users/jamiltao/.rvm/gems/ruby-1.8.7-p299@cj_pivot/gems/massive_record-0.1.1/lib/massive_record/orm/config.rb:17:in
`connection'
    from
/Users/jamiltao/.rvm/gems/ruby-1.8.7-p299@cj_pivot/gems/massive_record-0.1.1/lib/massive_record/orm/persistence.rb:152:in
`ensure_that_we_have_table_and_column_families!'
    from
/Users/jamiltao/.rvm/gems/ruby-1.8.7-p299@cj_pivot/gems/massive_record-0.1.1/lib/massive_record/orm/persistence.rb:119:in
`create'
    from
/Users/jamiltao/.rvm/gems/ruby-1.8.7-p299@cj_pivot/gems/massive_record-0.1.1/lib/massive_record/orm/callbacks.rb:44:in
`create'
    from
/Users/jamiltao/.rvm/gems/ruby-1.8.7-p299@cj_pivot/gems/activesupport-3.0.5/lib/active_support/callbacks.rb:420:in
`_run_create_callbacks'
    from
/Users/jamiltao/.rvm/gems/ruby-1.8.7-p299@cj_pivot/gems/massive_record-0.1.1/lib/massive_record/orm/callbacks.rb:44:in
`create'
    from
/Users/jamiltao/.rvm/gems/ruby-1.8.7-p299@cj_pivot/gems/massive_record-0.1.1/lib/massive_record/orm/persistence.rb:115:in
`create_or_update'
    from
/Users/jamiltao/.rvm/gems/ruby-1.8.7-p299@cj_pivot/gems/massive_record-0.1.1/lib/massive_record/orm/callbacks.rb:40:in
`create_or_update'
    from
/Users/jamiltao/.rvm/gems/ruby-1.8.7-p299@cj_pivot/gems/activesupport-3.0.5/lib/active_support/callbacks.rb:413:in
`_run_save_callbacks'
    from
/Users/jamiltao/.rvm/gems/ruby-1.8.7-p299@cj_pivot/gems/massive_record-0.1.1/lib/massive_record/orm/callbacks.rb:40:in
`create_or_update'
    from
/Users/jamiltao/.rvm/gems/ruby-1.8.7-p299@cj_pivot/gems/massive_record-0.1.1/lib/massive_record/orm/persistence.rb:38:in
`save'
    from
/Users/jamiltao/.rvm/gems/ruby-1.8.7-p299@cj_pivot/gems/massive_record-0.1.1/lib/massive_record/orm/attribute_methods/dirty.rb:10:in
`save'
    from
/Users/jamiltao/.rvm/gems/ruby-1.8.7-p299@cj_pivot/gems/massive_record-0.1.1/lib/massive_record/orm/validations.rb:36:in
`save'
    from (irb):14

I figured out that it was because :connection_configuration was coming up nil for some reason. I'm pretty sure I missed something somewhere, but i can't seem to figure out what I missed. 

BTW, when I use MassiveRecord::Wrapper::Base.connection it works fine

Thanks!

Edit: Using v0.1.1

**Comment by thhermansen** [comment]
Are you using Rails? If so create hbase.yml in your config file. See "Installation - Ruby on Rails" in the readme. If you are not on Rails you can set a connection config hash on ORM::Base manually like this:

```
MassiveRecord::ORM::Base.connection_configuration = {
  :host => 'hbase.host.com',
  :port => 9090
}
```

Did that help?

**Comment by jamiltao** [comment]
I am using rails, my hbase.yml looks like this

defaults: &defaults
  host:*********************.com # No 'http', it's a Thrift connection
  port: 9090

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

**Comment by thhermansen** [comment]
I did some testing myself now with ruby 1.8.7, and after taken a look at the code I realize that MassiveRecord is currently not that supportive of ruby 1.8.7. So, if it is possible for you upgrade to 1.9.2. I will also advice you to use v0.2.0. Even though it's beta, it has improvements over 0.1.1.

**Comment by jamiltao** [comment]
Ok, I'll give it a shot! thanks!

**Comment by thhermansen** [comment]
You are welcome :) I'm not sure how much work it will be making it 1.8.7 compatible, but I guess its possible if someone really needs 1.8.7 support. Anyway, let me know if you encounter problems on 1.9.2.
