### ISSUE TITLE
Warning when starting rails console

### ISSUE THREAD

**Issue by jamiltao** [CompanyBook/massive_record#28]
I get the following warnings when running rails c

/usr/local/rvm/gems/ruby-1.8.7-p334@cj_pivot/gems/massive_record-0.1.1/lib/massive_record/wrapper/cell.rb:41: warning: regexp has invalid interval
/usr/local/rvm/gems/ruby-1.8.7-p334@cj_pivot/gems/massive_record-0.1.1/lib/massive_record/wrapper/cell.rb:41: warning: regexp has `}' without escape

probably just a typo somewhere

Using v0.1.1 btw

**Comment by thhermansen** [comment]
Hi,

The related code has been rewritten in 0.2.0 beta, so I'll close this one :-)
