### ISSUE TITLE
Question on references_many

### ISSUE THREAD

**Issue by jamiltao** [CompanyBook/massive_record#38]
Hi, I need to use references_many in my users model. When adding records, i run something like this:

interests.each do |i|
    user.interests.<< UserInterest.create!( :id => MassiveRecord::ORM::IdFactory.next_for(UserInterest), :interest_key => i.id, :name => i.name )
end

in the user model I have :  references_many :interests, :class_name => "UserInterest", :store_in => :info

So the UserInterest saves, and the ids appear in the interest_ids column in the User record. The problem is when I run user.interests, it returns an empty array.

Any Idea what I'm doing wrong?

**Comment by thhermansen** [comment]
Hi,

First, a couple of tips. In your models you can do:

```
class UserInterest < MassiveRecord::ORM::Table
  # default_id is called if id is nil when you try to read an id (for instance when saved if called)
  def default_id
    # next_id() goes via the IdFactory to figure out the
    # next id for the class. You can ofc do whatever you want here :-)
    next_id
  end
end
```

This will result in next id for your class, just like you do above.

Have you tried `user.interests.reload` to see if it returns something? As far as I can see you are using it correctly, so maybe there is a bug here too.

**Comment by jamiltao** [comment]
I read in your issues that there was a method like next_id(), but I
couldn't find it, thanks for the tip! I'll give reload a try, I'll let
you know what happens

**Comment by jamiltao** [comment]
no luck with user.interests.reload :( still returns an empty array

```
ruby-1.9.2-p180 :001 > u = HbaseUser.first
=> #<HbaseUser id: "10", profile_id: "10", interest_ids: [33, 34, 35, 36, 37], button_ids: [], first_name: "Test",   last_name: "User", email: "user@test.com", password: nil, updated_at: "2011-05-25 22:42:46 -0400"> 
ruby-1.9.2-p180 :002 > u.interests
=> [] 
ruby-1.9.2-p180 :003 > u.interests.reload
=> [] 
```

**Comment by thhermansen** [comment]
Oki, I'll see if I have the time this weekend to test it myself with a simple Rails application or something :-)

**Comment by jamiltao** [comment]
awesome thanks, I'll wait for your findings :) If you don't mind sharing
the code for the sample app, it would be a big help to me :)

**Comment by thhermansen** [comment]
Hi again!

I have set up a test / example application here https://github.com/thhermansen/massive_record_test_app where I did test references many. Seems to me that it's working fine. You can take a look at it to see if you spot something different from what you do.

The test application contains some comments to the examples, plus some very basic rspec tests which are all passing. Hope it helps - please tell me how it goes :-)

**Comment by jamiltao** [comment]
I went through the sample app, and tried out the different ways to use references_many, and nothing was working until i decided to use the develop branch instead of the gem. Once I did that, everything started working properly. So somewhere in between the last gem release and the current develop branch, references_many wasn't working :p

Thanks for the sample app, it would be great if you could keep updating it in your free time to show off massive_record's features.

BTW, (and this should probably be a separate post) I don't suppose you have gotten devise to play nicely with massive_record? And in case you are interested, I modified a paperclip module for mongodb to work with massive_record (https://github.com/jamiltao/massive-record-paperclip)

**Comment by thhermansen** [comment]
I have gotten devise to work. It was a bit hackish, but I can put up the code for it in the example app :-) Guess its time to write some wiki pages as well soon hehe. Good to see you have implemented paperclip support. I have used Carrierwave for attachments in Companybook's project.

**Comment by thhermansen** [comment]
For a how-to on Devise, see: https://github.com/CompanyBook/massive_record/wiki/MassiveRecord-and-Devise. I hope that I wrote something which are possible to understand :-p
