### ISSUE TITLE
Auto-create IDs for new records

### ISSUE THREAD

**Issue by thhermansen** [CompanyBook/massive_record#4]
An idea is to have read-method for ID to check for default_id() or something like that on new records so we don't have to explicitly set it on creation. A lot of use cases in hbase, the key is just a composite string defined from some of it's attributes arranged in some pre-defined way. So I guess it can be convenient to have something like that?

**Comment by trym** [comment]
Thoughts after discussion among th+vp+ts
- Have an instance method (#generate_id / whatever) that could/should be overridden in the model to compose the key
- Provide a method that gives you an auto incremented number for the current table (which can be used in #generate_id)
  - Have a shared meta-table (auto_increment_counters / whatever) that has one row per table and uses the table name as the key and the value is the current counter value

**Comment by birgerlie** [comment]
could we not just have one table with all the objects, prefixed by classname? why use several tables... better with few tables so caching is more optimized

**Comment by trym** [comment]
Of course :) Thats what I mean by shared meta-table.

**Comment by thhermansen** [comment]
Implemented in master.
