### ISSUE TITLE
validates_presence_of , :on doesn't seem to be working

### ISSUE THREAD

**Issue by jamiltao** [CompanyBook/massive_record#49]
I need validates_presence_of to work with update only, but when I pass arguments to :on, the validations stop working completely

**Comment by thhermansen** [comment]
Thanks. I do believe I encountered this one myself as well, but I worked around it and forgot to add it as an issue in MassiveRecord.

**Comment by jamiltao** [comment]
Yeah, I validated the fields manually for now, but it would be nice to
validate it in the model eventually :)
