### ISSUE TITLE
Closed stream (timeout on connection)

### ISSUE THREAD

**Issue by thhermansen** [CompanyBook/massive_record#5]
Seems like we have a problem related to timeouts on the connection. On the ORM::Base, connection is keept as a class variable and reused. If a server process is idle for some time we might end up with a IOError (closed stream). So, it needs to be solved by reconnecting I guess :-)

**Comment by atbrox** [comment]
fyi - reconnecting works nicely, but not during scans, then it starts rescanning, which can be a costly thing to do on large tables (probably not an issues for the ui though)

**Comment by thhermansen** [comment]
The problem is with the ORM::Base which keeps it's reference to a connection object (which in turn I guess gets it's IO stream closed by the server if idle for some time). We have to catch this and try to reconnect and I don't think this is closed yet. I reopened it :-)

**Comment by thhermansen** [comment]
Vincent has fixed this in: https://github.com/CompanyBook/massive_record/commit/261775271afe8f3f5ae680e584b0e6dc2b538175
