### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by rails-learner** [CompanyBook/massive_record#81]
Is there any way to run this kind of query in massive record 
Query: "select from table name where h\* = any_value"

h\* is something where all column name starts with h and have value = any_value

**Comment by vincentp** [comment]
Hey, this kind of filtering is not available in massive record. I think you should work on your key to get the expected result and start scanning items starting a specific point: 
Cars.all(:start_with => "Citroen-")
will return:
Citroen-C1
Citroen-C2
...

**Comment by thunder14enator** [comment]
is it possible to fetch rows on the basis column qualifier , like i want to fetch all the row whose column qualifier starts with Citroen-C1
_-C1-_.. 
is there anything something like this in gem

**Comment by vincentp** [comment]
Unfortunately this is down to SQL language and doesn't work with HBase. 
You need to use a language on top of HBase like Pig to be able to do so.
Again, I think that most of the issues when it comes to sorting / searching can be fixed using a proper key ID.
For the really specific use, we are building another table which fits with our need using map/reduce.

**Comment by thunder14enator** [comment]
I researched it with JAVA that we can do this kind of searching using filters ,is there any way to use filters with massive record

**Comment by vincentp** [comment]
The Thrift API is not as advanced as the Java API, I saw that the new HBase version will have a way better Thrift API, this might be in the list. I'm sorry but I haven't checked yet!

**Comment by thhermansen** [comment]
I'm closing this for now. Maybe in the future it will be possible if we write an adapter for jruby which uses the java api, or a better Thrift API.
