### ISSUE TITLE
Inheritance and table_name

### ISSUE THREAD

**Issue by corywilkerson** [CompanyBook/massive_record#83]
Maybe I'm missing something obvious but I'm noticing that I can't explicitly set table name (using set_table_name) when I've inherited from a superclass.

For instance:

``` ruby
class Foo < MassiveRecord::ORM::Table
  default_scope select(:d)

  column_family :d do
    field :foo, :integer
  end
end

class Bar < Foo
  set_table_name "crazy-bars"
end
```

When I go to query Bar.first, for example, it infers the table name from "foo" and I'm left looking "foos" (in the Rails log and in Thrift you can see a lookup on "Foos") which is not at all what I'm after...

This is happening in 0.2.1.

Let me know if you need any additional info - this is my first GitHub issue report. Looking forward to learning how to contribute and assisting.

**Comment by vincentp** [comment]
hey, I will have a look at it next week :)
For now, you can probably set the table name using:

class Bar < Foo
  @table_name = "crazy-bars"
end

**Comment by corywilkerson** [comment]
I'll give it a shot and report back tomorrow.

Happy new year!

**Comment by corywilkerson** [comment]
Back at it - still remains an issue. We were able to get around this but moving the column definition off to a module and then extending the class on module include...
